// ============================================================================
// WebServerManager.cpp - ESP32 Web Server Implementation
// ============================================================================

#include "esp_https_server.h"
#include "esp_ota_ops.h"
#include "esp_system.h"
#include "app_event_loop.hpp"
#include "fmt/ranges.h"
#include "WebServerManager.hpp"
#include "ConfigManager.hpp"
#include "HomeSpan.h"
#include "MqttManager.hpp"
#include "NfcManager.hpp"
#include "ReaderDataManager.hpp"
#include "cJSON.h"
#include "config.hpp"
#include "esp_chip_info.h"
#include "esp_err.h"
#include "esp_heap_caps.h"
#include "esp_http_server.h"
#include "esp_log.h"
#include "esp_log_level.h"
#include "esp_wifi.h"
#include "eth_structs.hpp"
#include "eventStructs.hpp"
#include "freertos/idf_additions.h"
#include "loggable.hpp"
#include "sodium/randombytes.h"
#include <LittleFS.h>
#include <algorithm>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <dirent.h>
#include <esp_app_desc.h>
#include <mutex>
#include <esp_tls_crypto.h>
#include <stdbool.h>
#include <string>
#include <thread>
#include <vector>